#!/bin/zsh
# Pastello's watchdog: reopens the app if it disappears from the menu bar
# without the user having quit it (macOS 26/27 sometimes crashes it on a Space
# switch — a ViewBridge bug, see Sources/ViewBridgeGuard.swift).
#
#   ./tools/watchdog.sh install     install and start the LaunchAgent
#   ./tools/watchdog.sh uninstall   stop and remove it
#   ./tools/watchdog.sh status      is it active? recent reopenings?
#
# It leaves "open at login" alone (that stays SMAppService, from the gear menu):
# the watchdog only steps in while the app is not running.
set -euo pipefail

LABEL="it.foolica.pastello.watchdog"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
SUPPORT="$HOME/Library/Application Support/Pastello"
RUNNER="$SUPPORT/watchdog.sh"
LOG="$HOME/Library/Logs/Pastello-watchdog.log"
DOMAIN="gui/$(id -u)"

write_runner() {
  mkdir -p "$SUPPORT"
  cat > "$RUNNER" <<'INNER'
#!/bin/sh
# Generated by tools/watchdog.sh — do not edit by hand.
set -u
APP_NAME="Pastello"
APP_PATH="/Applications/Pastello.app"
MARKER="$HOME/Library/Application Support/Pastello/clean-exit"
STATE="$HOME/Library/Caches/it.foolica.pastello.watchdog.missing"
LOG="$HOME/Library/Logs/Pastello-watchdog.log"
# The app must look absent for at least two rounds before we reopen it: during
# a reinstall or an update it goes away for a few seconds and comes back on its
# own, and reopening it midway would mean launching a half-copied bundle.
GRACE=120

if pgrep -x "$APP_NAME" >/dev/null 2>&1; then rm -f "$STATE"; exit 0; fi
# Deliberate exit (Quit from the menu, logout, update): none of our business.
if [ -f "$MARKER" ]; then rm -f "$STATE"; exit 0; fi
[ -d "$APP_PATH" ] || exit 0

now=$(date +%s)
since=""
[ -f "$STATE" ] && since=$(cat "$STATE" 2>/dev/null)
case "$since" in ''|*[!0-9]*) since="$now"; printf '%s' "$now" > "$STATE" ;; esac
[ $((now - since)) -ge $GRACE ] || exit 0

printf '%s reopening %s (absent for %ss, exit was not clean)\n' \
  "$(date '+%Y-%m-%d %H:%M:%S')" "$APP_NAME" "$((now - since))" >> "$LOG"
rm -f "$STATE"
# -g: back in the menu bar without stealing focus from what you are doing.
open -g "$APP_PATH"
INNER
  chmod +x "$RUNNER"
}

write_plist() {
  mkdir -p "$HOME/Library/LaunchAgents"
  cat > "$PLIST" <<PL
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>$RUNNER</string>
    </array>
    <key>StartInterval</key><integer>60</integer>
    <key>RunAtLoad</key><true/>
    <key>LimitLoadToSessionType</key><string>Aqua</string>
    <key>ProcessType</key><string>Background</string>
    <key>StandardErrorPath</key><string>$LOG</string>
</dict>
</plist>
PL
}

case "${1:-install}" in
  install)
    write_runner
    write_plist
    launchctl bootout "$DOMAIN/$LABEL" 2>/dev/null || true
    launchctl bootstrap "$DOMAIN" "$PLIST"
    echo "✓ watchdog installed ($LABEL, checks every 60s)"
    echo "  runner: $RUNNER"
    echo "  log:    $LOG"
    ;;
  uninstall)
    launchctl bootout "$DOMAIN/$LABEL" 2>/dev/null || true
    rm -f "$PLIST" "$RUNNER" "$HOME/Library/Caches/it.foolica.pastello.watchdog.missing"
    echo "✓ watchdog removed"
    ;;
  status)
    if launchctl print "$DOMAIN/$LABEL" >/dev/null 2>&1; then
      echo "✓ watchdog active"
    else
      echo "✗ watchdog not active (./tools/watchdog.sh install)"
    fi
    if [ -f "$LOG" ]; then echo "— recent reopenings:"; tail -5 "$LOG"; fi
    ;;
  *)
    echo "usage: $0 [install|uninstall|status]" >&2
    exit 2
    ;;
esac
